[package]
name = "hexing"
version = "0.1.0"
edition = "2021"
description = "A basic Rust library to manipulate hexagonal grids."
repository = "https://github.com/CoCoSol007/hexing"
authors = ["CoCoSol"]
license = "GPLv3"
readme = "README.md"
keywords = [
  "Hex Grids",
  "Rust",
  "Hex Coordinates",
  "Distance",
  "Grid Tools",
  "Positions",
  "Pixel Conversion",
  "Ring Iterators",
  "Spiral Iterators",
  "Axial",
  "Algorithms",
  "Geometry",
  "Transformation",
  "Math"
]


[lints.rust]
missing_docs = "warn"

[lints.clippy]
missing_docs_in_private_items = "warn"
unwrap_in_result = "warn"
unwrap_used = "warn"
nursery = { level = "warn", priority = -1 }

[dependencies]
paste = "1.0.15"
